/*
 * This file was automatically generated by EvoSuite
 * Tue May 30 13:45:08 CEST 2017
 */

package Actions;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import java.util.ArrayList;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import Components.Card;
import Components.Floor;
import Components.HarvestAndProductionArea;
import Components.Relative;
import Components.Tower;
import it.polimi.ingsw.GC_40.ColorDice;
import it.polimi.ingsw.GC_40.ColorPlayer;
import it.polimi.ingsw.GC_40.Player;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PutRelative_ESTest extends PutRelative_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.RED;
      Player player0 = new Player(colorPlayer0);
      ColorDice colorDice0 = ColorDice.WHITE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnProductionArea putRelativeOnProductionArea0 = new PutRelativeOnProductionArea(player0, relative0);
      HarvestAndProductionArea harvestAndProductionArea0 = new HarvestAndProductionArea();
      putRelativeOnProductionArea0.productionArea = harvestAndProductionArea0;
      boolean boolean0 = putRelativeOnProductionArea0.isApplicable();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.GREEN;
      Player player0 = new Player(colorPlayer0);
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace(player0, relative0);
      boolean boolean0 = putRelativeOnCouncilPalace0.isApplicable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.RED;
      Player player0 = new Player(colorPlayer0);
      PutRelativeOnProductionArea putRelativeOnProductionArea0 = new PutRelativeOnProductionArea(player0, (Relative) null);
      // Undeclared exception!
      try { 
        putRelativeOnProductionArea0.isApplicable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Actions.PutRelativeOnProductionArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.BLUE;
      Player player0 = new Player(colorPlayer0);
      ArrayList<Card> arrayList0 = new ArrayList<Card>();
      ArrayList<Floor> arrayList1 = new ArrayList<Floor>();
      Tower tower0 = new Tower("", arrayList0, arrayList0, arrayList0, arrayList1);
      PutRelativeOnTower putRelativeOnTower0 = new PutRelativeOnTower(player0, tower0, 0, (Relative) null);
      // Undeclared exception!
      try { 
        putRelativeOnTower0.isApplicable();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.GREEN;
      Player player0 = new Player(colorPlayer0);
      ArrayList<Card> arrayList0 = new ArrayList<Card>();
      ArrayList<Floor> arrayList1 = new ArrayList<Floor>();
      Tower tower0 = new Tower("", arrayList0, arrayList0, arrayList0, arrayList1);
      PutRelativeOnTower putRelativeOnTower0 = new PutRelativeOnTower(player0, tower0, (-1), (Relative) null);
      // Undeclared exception!
      try { 
        putRelativeOnTower0.isApplicable();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.GREEN;
      Player player0 = new Player(colorPlayer0);
      PutRelativeOnMarket putRelativeOnMarket0 = new PutRelativeOnMarket(player0, (Relative) null);
      // Undeclared exception!
      try { 
        putRelativeOnMarket0.apply();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Actions.PutRelativeOnMarket", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.GREEN;
      Player player0 = new Player(colorPlayer0);
      ArrayList<Card> arrayList0 = new ArrayList<Card>();
      ArrayList<Floor> arrayList1 = new ArrayList<Floor>();
      Tower tower0 = new Tower("", arrayList0, arrayList0, arrayList0, arrayList1);
      PutRelativeOnTower putRelativeOnTower0 = new PutRelativeOnTower(player0, tower0, 0, (Relative) null);
      // Undeclared exception!
      try { 
        putRelativeOnTower0.apply();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.YELLOW;
      Player player0 = new Player(colorPlayer0);
      ArrayList<Card> arrayList0 = new ArrayList<Card>();
      ArrayList<Floor> arrayList1 = new ArrayList<Floor>();
      Tower tower0 = new Tower("", arrayList0, arrayList0, arrayList0, arrayList1);
      PutRelativeOnTower putRelativeOnTower0 = new PutRelativeOnTower(player0, tower0, (-1), (Relative) null);
      // Undeclared exception!
      try { 
        putRelativeOnTower0.apply();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.WHITE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0);
      putRelativeOnCouncilPalace0.apply();
  }
}
