/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 08:32:49 CEST 2017
 */

package it.polimi.ingsw.actions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import it.polimi.ingsw.GC_40.Player;
import it.polimi.ingsw.actions.PutRelativeOnProductionArea;
import it.polimi.ingsw.components.Relative;
import java.util.UUID;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PutRelativeOnProductionArea_ESTest extends PutRelativeOnProductionArea_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Player player0 = new Player();
      PutRelativeOnProductionArea putRelativeOnProductionArea0 = new PutRelativeOnProductionArea(player0, (Relative) null, "right");
      // Undeclared exception!
      try { 
        putRelativeOnProductionArea0.isApplicable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.actions.PutRelativeOnProductionArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UUID uUID0 = new UUID(0L, 0L);
      Player player0 = new Player(uUID0);
      PutRelativeOnProductionArea putRelativeOnProductionArea0 = new PutRelativeOnProductionArea(player0, (Relative) null, "");
      putRelativeOnProductionArea0.apply(null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Player player0 = new Player();
      PutRelativeOnProductionArea putRelativeOnProductionArea0 = new PutRelativeOnProductionArea(player0, (Relative) null, "right");
      // Undeclared exception!
      try { 
        putRelativeOnProductionArea0.apply(null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.actions.PutRelativeOnProductionArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PutRelativeOnProductionArea putRelativeOnProductionArea0 = new PutRelativeOnProductionArea((Player) null, (Relative) null, "left");
      // Undeclared exception!
      try { 
        putRelativeOnProductionArea0.isApplicable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.actions.PutRelativeOnProductionArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Player player0 = new Player();
      PutRelativeOnProductionArea putRelativeOnProductionArea0 = new PutRelativeOnProductionArea(player0, (Relative) null, "");
      boolean boolean0 = putRelativeOnProductionArea0.isApplicable();
      assertFalse(boolean0);
  }
}
