/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 08:28:22 CEST 2017
 */

package it.polimi.ingsw.actions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import it.polimi.ingsw.GC_40.Player;
import it.polimi.ingsw.actions.PutRelativeOnCouncilPalace;
import it.polimi.ingsw.areas.CouncilPalace;
import it.polimi.ingsw.colors.ColorDice;
import it.polimi.ingsw.components.Relative;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PutRelativeOnCouncilPalace_ESTest extends PutRelativeOnCouncilPalace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      relative0.setValue(1);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0, "");
      CouncilPalace councilPalace0 = new CouncilPalace(0, 0, 0);
      putRelativeOnCouncilPalace0.councilPalace = councilPalace0;
      // Undeclared exception!
      try { 
        putRelativeOnCouncilPalace0.apply();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.areas.CouncilPalace", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Player player0 = new Player();
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace(player0, (Relative) null, "");
      // Undeclared exception!
      try { 
        putRelativeOnCouncilPalace0.isApplicable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.actions.PutRelativeOnCouncilPalace", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.BLACK;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0, "");
      putRelativeOnCouncilPalace0.apply();
      assertFalse(putRelativeOnCouncilPalace0.isApplicable());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      relative0.setValue(1);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0, "");
      boolean boolean0 = putRelativeOnCouncilPalace0.isApplicable();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.WHITE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0, "");
      boolean boolean0 = putRelativeOnCouncilPalace0.isApplicable();
      assertFalse(boolean0);
  }
}
