/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 08:31:20 CEST 2017
 */

package it.polimi.ingsw.actions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import it.polimi.ingsw.GC_40.Player;
import it.polimi.ingsw.actions.PutRelativeOnHarvestArea;
import it.polimi.ingsw.components.Relative;
import java.util.UUID;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PutRelativeOnHarvestArea_ESTest extends PutRelativeOnHarvestArea_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Player player0 = new Player((UUID) null);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea(player0, (Relative) null, "right");
      // Undeclared exception!
      try { 
        putRelativeOnHarvestArea0.apply(null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.actions.PutRelativeOnHarvestArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Player player0 = new Player();
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea(player0, (Relative) null, "");
      putRelativeOnHarvestArea0.apply(null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Player player0 = new Player((UUID) null);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea(player0, (Relative) null, "right");
      // Undeclared exception!
      try { 
        putRelativeOnHarvestArea0.isApplicable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.actions.PutRelativeOnHarvestArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Player player0 = new Player();
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea(player0, (Relative) null, "left");
      // Undeclared exception!
      try { 
        putRelativeOnHarvestArea0.isApplicable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.actions.PutRelativeOnHarvestArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Player player0 = new Player();
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea(player0, (Relative) null, "");
      boolean boolean0 = putRelativeOnHarvestArea0.isApplicable();
      assertFalse(boolean0);
  }
}
