/*
 * This file was automatically generated by EvoSuite
 * Tue May 30 13:42:19 CEST 2017
 */

package Actions;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import Components.HarvestAndProductionArea;
import Components.Relative;
import it.polimi.ingsw.GC_40.ColorDice;
import it.polimi.ingsw.GC_40.ColorPlayer;
import it.polimi.ingsw.GC_40.Player;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PutRelativeOnHarvestArea_ESTest extends PutRelativeOnHarvestArea_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      relative0.setValue(779541771);
      relative0.setValue(1757712763);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea((Player) null, relative0);
      HarvestAndProductionArea harvestAndProductionArea0 = new HarvestAndProductionArea();
      putRelativeOnHarvestArea0.harvestArea = harvestAndProductionArea0;
      relative0.setValue(1757712763);
      // Undeclared exception!
      try { 
        putRelativeOnHarvestArea0.apply();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Effects.GainHarvestValue", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      relative0.setValue(779541770);
      relative0.setValue(1757712763);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea((Player) null, relative0);
      HarvestAndProductionArea harvestAndProductionArea0 = new HarvestAndProductionArea();
      putRelativeOnHarvestArea0.harvestArea = harvestAndProductionArea0;
      relative0.setValue(1757712763);
      // Undeclared exception!
      try { 
        putRelativeOnHarvestArea0.apply();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Effects.GainHarvestValue", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.YELLOW;
      Player player0 = new Player(colorPlayer0);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea(player0, (Relative) null);
      // Undeclared exception!
      try { 
        putRelativeOnHarvestArea0.isApplicable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Actions.PutRelativeOnHarvestArea", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.WHITE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea((Player) null, relative0);
      HarvestAndProductionArea harvestAndProductionArea0 = new HarvestAndProductionArea();
      putRelativeOnHarvestArea0.harvestArea = harvestAndProductionArea0;
      ColorPlayer colorPlayer0 = ColorPlayer.YELLOW;
      Player player0 = new Player(colorPlayer0);
      putRelativeOnHarvestArea0.harvestArea.setLeftPlayer(player0);
      // Undeclared exception!
      try { 
        putRelativeOnHarvestArea0.apply();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Effects.GainHarvestValue", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      relative0.setValue(389770885);
      relative0.setValue(1757712763);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea((Player) null, relative0);
      HarvestAndProductionArea harvestAndProductionArea0 = new HarvestAndProductionArea();
      putRelativeOnHarvestArea0.harvestArea = harvestAndProductionArea0;
      putRelativeOnHarvestArea0.apply();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.WHITE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea((Player) null, relative0);
      putRelativeOnHarvestArea0.harvestArea = null;
      HarvestAndProductionArea harvestAndProductionArea0 = new HarvestAndProductionArea();
      putRelativeOnHarvestArea0.harvestArea = harvestAndProductionArea0;
      boolean boolean0 = putRelativeOnHarvestArea0.isApplicable();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.WHITE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnHarvestArea putRelativeOnHarvestArea0 = new PutRelativeOnHarvestArea((Player) null, relative0);
      putRelativeOnHarvestArea0.harvestArea = null;
      relative0.setValue((-1));
      HarvestAndProductionArea harvestAndProductionArea0 = new HarvestAndProductionArea();
      putRelativeOnHarvestArea0.harvestArea = harvestAndProductionArea0;
      boolean boolean0 = putRelativeOnHarvestArea0.isApplicable();
      assertFalse(boolean0);
  }
}
