/*
 * This file was automatically generated by EvoSuite
 * Tue May 30 13:43:53 CEST 2017
 */

package it.polimi.ingsw.actions;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.Test;
import org.junit.runner.RunWith;

import it.polimi.ingsw.components.*;
import it.polimi.ingsw.resources.Coin;
import it.polimi.ingsw.areas.*;
import it.polimi.ingsw.colors.*;
import it.polimi.ingsw.GC_40.Player;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class PutRelativeOnCouncilPalace_ESTest extends PutRelativeOnCouncilPalace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.GREEN;
      Player player0 = new Player(colorPlayer0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace(player0, (Relative) null);
      Coin coin0 = new Coin();
      putRelativeOnCouncilPalace0.setPiece(coin0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0);
      CouncilPalace councilPalace0 = new CouncilPalace();
      putRelativeOnCouncilPalace0.councilPalace = councilPalace0;
      relative0.setValue(1);
      // Undeclared exception!
      try { 
        putRelativeOnCouncilPalace0.apply();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Components.CouncilPalace", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ColorPlayer colorPlayer0 = ColorPlayer.BLUE;
      Player player0 = new Player(colorPlayer0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace(player0, (Relative) null);
      // Undeclared exception!
      try { 
        putRelativeOnCouncilPalace0.isApplicable();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Actions.PutRelativeOnCouncilPalace", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0);
      boolean boolean0 = putRelativeOnCouncilPalace0.isApplicable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0);
      relative0.setValue(1);
      boolean boolean0 = putRelativeOnCouncilPalace0.isApplicable();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ColorDice colorDice0 = ColorDice.ORANGE;
      Relative relative0 = new Relative(colorDice0);
      PutRelativeOnCouncilPalace putRelativeOnCouncilPalace0 = new PutRelativeOnCouncilPalace((Player) null, relative0);
      putRelativeOnCouncilPalace0.apply();
      assertFalse(putRelativeOnCouncilPalace0.isApplicable());
  }
}
