/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 08:34:07 CEST 2017
 */

package it.polimi.ingsw.actions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import it.polimi.ingsw.GC_40.Observer;
import it.polimi.ingsw.actions.RegisterClient;
import it.polimi.ingsw.changes.Change;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class RegisterClient_ESTest extends RegisterClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RegisterClient registerClient0 = new RegisterClient();
      registerClient0.registerObserver((Observer<Change>) null);
      // Undeclared exception!
      try { 
        registerClient0.apply(null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("it.polimi.ingsw.GC_40.Observable", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RegisterClient registerClient0 = new RegisterClient();
      registerClient0.apply(null);
  }
}
