/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Jun 08 08:41:12 CEST 2017
 */

package it.polimi.ingsw.GC_40;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class Play_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "it.polimi.ingsw.GC_40.Play"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Play_ESTest_scaffolding.class.getClassLoader() ,
      "it.polimi.ingsw.GC_40.Play",
      "it.polimi.ingsw.components.Relative",
      "org.json.simple.JSONStreamAware",
      "org.json.simple.JSONAware",
      "it.polimi.ingsw.GC_40.Observable",
      "org.json.simple.JSONArray",
      "it.polimi.ingsw.components.PersonalBonusTile",
      "it.polimi.ingsw.cards.Card",
      "org.json.simple.parser.ParseException",
      "org.json.simple.JSONValue",
      "it.polimi.ingsw.areas.Floor",
      "org.json.simple.parser.Yytoken",
      "it.polimi.ingsw.effects.Effect",
      "it.polimi.ingsw.colors.ColorDice",
      "it.polimi.ingsw.effects.GainCoin",
      "it.polimi.ingsw.GC_40.Board",
      "it.polimi.ingsw.changes.Change",
      "it.polimi.ingsw.effects.GainMilitaryPoint",
      "org.json.simple.parser.JSONParser",
      "it.polimi.ingsw.colors.ColorPlayer",
      "it.polimi.ingsw.GC_40.JSon",
      "org.json.simple.parser.Yylex",
      "it.polimi.ingsw.components.FinalVictoryPoint",
      "it.polimi.ingsw.areas.MarketBuilding",
      "it.polimi.ingsw.GC_40.Observer",
      "it.polimi.ingsw.effects.GainWood",
      "org.json.simple.JSONObject",
      "it.polimi.ingsw.areas.CouncilPalace",
      "it.polimi.ingsw.GC_40.Player",
      "it.polimi.ingsw.effects.GainStone",
      "it.polimi.ingsw.changes.ChangeTurnOrder",
      "it.polimi.ingsw.components.PrivilegeCouncil"
    );
  } 
}
