/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 08 08:41:12 CEST 2017
 */

package it.polimi.ingsw.GC_40;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import it.polimi.ingsw.GC_40.Play;
import it.polimi.ingsw.GC_40.Player;
import it.polimi.ingsw.colors.ColorDice;
import it.polimi.ingsw.components.Relative;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(useVNET = true, separateClassLoader = true, useJEE = true) 
public class Play_ESTest extends Play_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      ColorDice colorDice0 = ColorDice.BLACK;
      Relative relative0 = new Relative(colorDice0);
      Player player0 = relative0.getPlayer();
      arrayList0.add(player0);
      ArrayList<Player> arrayList1 = Play.createTurnOrder(arrayList0);
      assertFalse(arrayList1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Play.createTurnOrder((ArrayList<Player>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Collections", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArrayList<Player> arrayList0 = new ArrayList<Player>();
      ArrayList<Player> arrayList1 = Play.createTurnOrder(arrayList0);
      assertEquals(0, arrayList1.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Play play0 = new Play();
  }
}
