/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Fri Jun 23 18:06:45 CEST 2017
 */

package it.polimi.ingsw.cards;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;

@EvoSuiteClassExclude
public class BuildingCard_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "it.polimi.ingsw.cards.BuildingCard"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 


  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(BuildingCard_ESTest_scaffolding.class.getClassLoader() ,
      "it.polimi.ingsw.GC_40.Play",
      "it.polimi.ingsw.changes.ChangeCoin",
      "it.polimi.ingsw.components.Relative",
      "org.json.simple.JSONStreamAware",
      "org.json.simple.JSONAware",
      "it.polimi.ingsw.GC_40.Observable",
      "it.polimi.ingsw.effects.GainVictoryPoint",
      "it.polimi.ingsw.cards.Card",
      "it.polimi.ingsw.components.PersonalBonusTile",
      "org.json.simple.JSONArray",
      "it.polimi.ingsw.cards.CreateListOfEffect",
      "org.json.simple.parser.ParseException",
      "org.json.simple.JSONValue",
      "org.json.simple.parser.Yytoken",
      "it.polimi.ingsw.effects.Effect",
      "it.polimi.ingsw.colors.ColorDice",
      "it.polimi.ingsw.effects.HasPrivilege",
      "it.polimi.ingsw.GC_40.Board",
      "it.polimi.ingsw.changes.Change",
      "org.json.simple.parser.JSONParser",
      "it.polimi.ingsw.colors.ColorPlayer",
      "it.polimi.ingsw.json.JsonCard",
      "it.polimi.ingsw.cards.BuildingListOfEffect",
      "org.json.simple.parser.Yylex",
      "it.polimi.ingsw.changes.ChangeWood",
      "it.polimi.ingsw.GC_40.Observer",
      "org.json.simple.JSONObject",
      "it.polimi.ingsw.changes.ChangeStone",
      "it.polimi.ingsw.effects.GainFaithPoint",
      "it.polimi.ingsw.cards.BuildingCard",
      "it.polimi.ingsw.GC_40.Player"
    );
  } 
}
